services:
  - type: web
    name: llms-generator-toolkit
    runtime: python
    pythonVersion: "3.11.8"
    buildCommand: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p /opt/render/.cache/ms-playwright
      python -m playwright install --force chromium
    startCommand: .venv/bin/gunicorn --bind 0.0.0.0:$PORT --timeout 600 app:server
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
