services:
  - type: web
    name: llms-generator-toolkit
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install
      python -m playwright install-deps
    startCommand: gunicorn app:server
    runtime: python
    pythonVersion: 3.11
    buildFilter:
      paths:
        - "**/*.py"
        - requirements.txt
        - render.yaml
