services:
  - type: web
    name: llms-generator-toolkit
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python3 -m playwright install
      python3 -m playwright install-deps
    startCommand: gunicorn app:server 
    runtime: python
    pythonVersion: 3.11
