services:
  - type: web
    name: llms-generator-toolkit
    runtime: python
    pythonVersion: "3.11.8"
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps chromium
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT --timeout 600
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
