services:
  - type: web
    name: llms-generator
    runtime: python
    pythonVersion: "3.11.8"
    buildCommand: |
      pip install -r requirements.txt
      playwright install
      playwright install-deps
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
